<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>89efe28c-6fe3-4a99-8a1c-2c8eef4a4ae5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.img-view > a > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bb-body']/div/div[4]/div/div/div/ul/li/div/div[2]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>170dc8d0-e8e3-4512-82d4-f9729f47bb29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//bookbuy.vn/Res/Images/Product/combo-qua-tang-cho-be-9-6-cuon-be-than-dong-vao-lop-1-4-cuon-to-mau-yeu-thuong-_122683_3.jpg?w=250&amp;h=350&amp;mode=canvas&amp;quality=90</value>
      <webElementGuid>65c2d6de-55da-46e4-aa61-7d984bbc507b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bb-body&quot;)/div[@class=&quot;home-page ng-scope&quot;]/div[@class=&quot;booktopic-group&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;body&quot;]/div[@class=&quot;items&quot;]/ul[1]/li[@class=&quot;item core b1&quot;]/div[@class=&quot;product-item&quot;]/div[@class=&quot;img-view&quot;]/a[1]/img[1]</value>
      <webElementGuid>6c8d0a00-8497-4def-a1b0-3d2fae5bd730</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bb-body']/div/div[4]/div/div/div/ul/li/div/div[2]/a/img</value>
      <webElementGuid>b0008033-f434-46f6-b9ac-8bb63a4120a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/ul/li/div/div[2]/a/img</value>
      <webElementGuid>48a88e3c-cfc8-47f3-9d5d-18e213b6bb8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//bookbuy.vn/Res/Images/Product/combo-qua-tang-cho-be-9-6-cuon-be-than-dong-vao-lop-1-4-cuon-to-mau-yeu-thuong-_122683_3.jpg?w=250&amp;h=350&amp;mode=canvas&amp;quality=90']</value>
      <webElementGuid>9c57ad45-68dc-4767-badb-86169a1e6ed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bb-body']/div/div[10]/div/div[2]/div[2]/div/div/data-owl-carousel/div/div/div/div/ul/li/div/div/a/img</value>
      <webElementGuid>9bc734c8-a938-4e0b-aeb2-3f2d986c09c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/data-owl-carousel/div/div/div/div/ul/li/div/div/a/img</value>
      <webElementGuid>80872d22-daff-4892-b248-5ff109b4fa6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//bookbuy.vn/Res/Images/Product/postcard-art-to-mau-cma-studio-giay-my-thuat-300gsm-cao-cap-10x15cm_122500_1.jpg?w=190&amp;mode=crop&amp;h=140']</value>
      <webElementGuid>bb485eaa-3d2e-40c2-8bd6-d4f4bf2c1e63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
