<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Lm p - Sc Khe_Term</name>
   <tag></tag>
   <elementGuidId>953cbbc5-04f8-48a4-8bad-51ceb87dde16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Term</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Term']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cb2e35a6-7ce9-49f5-8c42-576f91bc862c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1708ed11-8f8e-4db5-8a64-d2820f0b0e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Term</value>
      <webElementGuid>9e5d7f4d-8a24-4d78-bdf6-24f2a07e6dee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Term</value>
      <webElementGuid>76a5d840-a55b-4a84-be8a-80fc38c815e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e745e2cd-b0ef-4cda-89c8-ce940b5c227b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Bạn cần tìm gì?</value>
      <webElementGuid>97ff6cf0-4db6-45dc-9be3-7b2e32ad4c6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ui-autocomplete-input</value>
      <webElementGuid>84f12a3c-d5be-4c50-aa8f-0299466a4dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Term&quot;)</value>
      <webElementGuid>fa7abedc-5f74-496f-bb58-25fdb2380b36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Term']</value>
      <webElementGuid>6d651948-a330-456d-902c-620ee39f2ff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bb-header']/div[2]/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>2a25abd8-f7e2-417c-a3cb-29990d9e9ae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/input</value>
      <webElementGuid>cda17131-c4e4-4970-a681-647186472c92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'Term' and @id = 'Term' and @placeholder = 'Bạn cần tìm gì?']</value>
      <webElementGuid>a7e702be-f32c-4872-b017-4d4bda9cde72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
