<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Combo Qu Tng Cho B 9_slimmage</name>
   <tag></tag>
   <elementGuidId>06b588ad-159b-4e62-9f00-2e235336c591</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.img-view > a > img.slimmage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bb-body']/div/div/div/div/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>01173476-9f68-448f-a362-0346b0be7d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slimmage</value>
      <webElementGuid>aeb62184-7f9b-447f-bb2b-92df26f4a9ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Res/Images/Product/combo-onikuma-9-tai-nghe-k9-pink-chuot-cw905-wireless-2-4g-pink-_133253_1.jpg?w=135&amp;h=180&amp;scale=canvas&amp;Cache=Always</value>
      <webElementGuid>672838c7-c6d3-4191-87c7-3c5305b643ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loaded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8719a426-7e43-4b19-ac3b-9d352e1de564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bb-body&quot;)/div[@class=&quot;search-result&quot;]/div[@class=&quot;product-list&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;product-list-content&quot;]/div[@class=&quot;product-item&quot;]/div[@class=&quot;img-view&quot;]/a[1]/img[@class=&quot;slimmage&quot;]</value>
      <webElementGuid>25c505b8-b220-41cf-bb15-4e8b44d77765</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bb-body']/div/div/div/div/div/div/a/img</value>
      <webElementGuid>e31c3357-443e-4e52-81ca-5a2a2b91e9e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/a/img</value>
      <webElementGuid>654018e2-9069-4531-8ef0-4e59cf90f939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/Res/Images/Product/combo-onikuma-9-tai-nghe-k9-pink-chuot-cw905-wireless-2-4g-pink-_133253_1.jpg?w=135&amp;h=180&amp;scale=canvas&amp;Cache=Always']</value>
      <webElementGuid>a49330ca-1db5-4b38-a0a5-4b3c4f4e6ad7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
