<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Vng,  ti mua thm_md-off</name>
   <tag></tag>
   <elementGuidId>8341fcb0-0c2c-407a-903f-bec3117639f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NomarShipping > div.md-container.md-ink-ripple > div.md-off</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//md-radio-button[@id='NomarShipping']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c586e1e0-701c-4fe4-b113-f433076ebcce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md-off</value>
      <webElementGuid>866232e5-fc6e-4568-89ee-9bf107f8ef2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NomarShipping&quot;)/div[@class=&quot;md-container md-ink-ripple&quot;]/div[@class=&quot;md-off&quot;]</value>
      <webElementGuid>1763e104-c952-4a4e-a4f2-7094feca8275</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//md-radio-button[@id='NomarShipping']/div/div</value>
      <webElementGuid>48911560-3a8d-4641-a350-5f1bacfc19a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/md-radio-group/md-radio-button/div/div</value>
      <webElementGuid>df694387-2afb-467c-948c-84c7b94d4db3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
