<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_S in thoi khng hp l_txtEditTelephone</name>
   <tag></tag>
   <elementGuidId>02beafe7-5f95-4075-a1c3-8a21e9cd1335</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtEditTelephone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtEditTelephone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d9412bf1-9f2e-405c-8e7a-91b92c81d290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-input input-text ng-pristine ng-empty ng-invalid ng-invalid-required ng-valid-pattern ng-touched</value>
      <webElementGuid>b2aea376-f450-48c3-8e06-84826cb57e61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f4a56945-e759-419c-8246-481dd813d736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-pattern</name>
      <type>Main</type>
      <value>/^[\s()+-]*([0-9][\s()+-]*){6,14}$/</value>
      <webElementGuid>45b1ea31-8391-43aa-9e69-e4e7f702733a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtEditTelephone</value>
      <webElementGuid>2fb3aac5-302f-483b-a38c-8f11a247c3d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtEditTelephone</value>
      <webElementGuid>35a95eb1-ad17-4d78-b6ca-bed42f7f151f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>editUserAdress.Address.Telephone</value>
      <webElementGuid>86913484-55c8-4106-a3f7-6e049eccb4c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0a52b865-505e-4e93-9f8f-9ec1687d7c9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>12d669fe-586c-4b5c-9267-59daedaa4bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtEditTelephone&quot;)</value>
      <webElementGuid>ac6ba24e-f9a6-4ced-96b4-feed4f8b661e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtEditTelephone']</value>
      <webElementGuid>5dc3f90e-bd40-4e6b-ac98-fbd206ba6204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bb-body']/div/div/div/form/div[2]/div[2]/div[16]/div[2]/p/input</value>
      <webElementGuid>f7dcfe42-9c0b-4fcf-8840-95b88e699297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div[2]/p/input</value>
      <webElementGuid>8709dfef-2847-4cba-9be2-ca1a3def38d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'txtEditTelephone' and @id = 'txtEditTelephone']</value>
      <webElementGuid>2e51132a-8f92-4006-835b-105b1eb283b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
