<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txtOrderEmail</name>
   <tag></tag>
   <elementGuidId>d0be4f94-2436-45a4-9726-2b92647481dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtOrderEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtOrderEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c9be029-ea2f-443f-ba11-c2f1377279ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-input input-text ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required ng-valid-pattern ng-not-empty-add ng-pristine-remove ng-dirty-add ng-valid-parse-add ng-valid-add ng-invalid-remove ng-valid-required-add ng-invalid-required-remove ng-valid-remove ng-invalid-add ng-valid-pattern-remove ng-invalid-pattern-add</value>
      <webElementGuid>41418e0d-4fe4-4d44-86aa-6f31b3cc0618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f11e8267-236e-4321-acb0-284cd7635451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtOrderEmail</value>
      <webElementGuid>0011bce1-c509-4289-9aad-5fdf74295a8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtOrderEmail</value>
      <webElementGuid>7f4a3f26-9dea-4dfb-9d4a-55701ca98a52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-pattern</name>
      <type>Main</type>
      <value>/^(([^&lt;>()[\]\\.,;:\s@\&quot;]+(\.[^&lt;>()[\]\\.,;:\s@\&quot;]+)*)|(\&quot;.+\&quot;))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/</value>
      <webElementGuid>19de8139-57f9-486b-9b87-614af1bd1d92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>editUserAdress.OrderEmail</value>
      <webElementGuid>9444cdd4-5011-4aa5-a777-6bc44cf95ead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>005e7ab8-33fe-4adc-88ac-b5352bdab778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>82733987-8522-4f91-9a40-6654bea31380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-animate</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>27cd8034-ce6e-428a-8cc0-6c46bb4ed519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtOrderEmail&quot;)</value>
      <webElementGuid>4ec87bb8-6c3a-4878-ba86-a6e66fb114fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtOrderEmail']</value>
      <webElementGuid>f1add376-63e8-46ba-b682-250bba5894df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bb-body']/div/div/div/form/div[2]/div[2]/div[4]/div[2]/p/input</value>
      <webElementGuid>f2e057b1-8d20-48a1-a63e-18d669136a1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/p/input</value>
      <webElementGuid>4ba515a7-f6bc-4a60-8f78-943de5e5a979</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtOrderEmail' and @name = 'txtOrderEmail']</value>
      <webElementGuid>fd7b5f69-13ef-470b-a73f-b8cb4f631770</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
