<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txtEditFullName</name>
   <tag></tag>
   <elementGuidId>b9fdd22a-83ed-4bf7-bed6-9fb6319aeb3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtEditFullName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtEditFullName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>38ec9204-5586-4cfc-aaae-563db7058811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-input input-text ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required</value>
      <webElementGuid>ae82f75d-edb4-439a-abc2-cde88b159c5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>33c9edd1-aa10-47c4-ad90-c8b8ebf5252f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtEditFullName</value>
      <webElementGuid>d4f3c5e1-8643-465e-bcc5-efa8fa8098cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtEditFullName</value>
      <webElementGuid>cfb12fcd-5eb1-42ae-846b-c80e18eeeaf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>editUserAdress.Address.FullName</value>
      <webElementGuid>0b70009c-d7e4-493c-a2bd-9871ab893339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6697d781-c4c5-45a2-9278-15ad70e199d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4cb8ace3-4a0c-4437-bcea-ec9724ddc898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtEditFullName&quot;)</value>
      <webElementGuid>fddd556b-f265-482e-954c-974951615ed0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtEditFullName']</value>
      <webElementGuid>843bd9dd-0168-4d1d-82a6-72834c7efa7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bb-body']/div/div/div/form/div[2]/div[2]/div[2]/div[2]/p/input</value>
      <webElementGuid>3c9af0bc-7479-43a5-9b87-642d03a8627d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>cbbc6da8-200e-4ea0-a226-299e715a4d94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtEditFullName' and @name = 'txtEditFullName']</value>
      <webElementGuid>9de242ba-bbc5-484e-b9fc-4a880fdd1d84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
