<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Ba nhHon KimTy HLong BinCu Giyng aHa_72188f</name>
   <tag></tag>
   <elementGuidId>ff380241-f915-43ed-872d-f1503b16c865</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dropEditWard</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dropEditWard']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e7272330-8565-4acf-b547-54432988aa0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-input input-text ng-pristine ng-untouched ng-valid ng-not-empty</value>
      <webElementGuid>39fea27a-fd7b-4572-ba8c-ecdf7f463dab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dropEditWard</value>
      <webElementGuid>41d9485e-1801-4a12-8299-397d6ab04a5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dropEditWard</value>
      <webElementGuid>8ddf0b21-d1b9-4684-a7b0-bb5a8cdb87e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>editUserAdress.Address.Ward</value>
      <webElementGuid>2bbd4c08-fbce-4fa2-a9d3-5e44686cd549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-options</name>
      <type>Main</type>
      <value>option.Name for option in recWards track by option.ID</value>
      <webElementGuid>e3923c22-6642-418b-b808-b61f8f269084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>05b78887-e17a-42e0-9b12-6badf1ca8d9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ba ĐìnhHoàn KiếmTây HồLong BiênCầu GiấyĐống ĐaHai Bà TrưngHoàng MaiThanh XuânSóc SơnĐông AnhGia LâmNam Từ LiêmThanh TrìMê LinhHà ĐôngSơn TâyBa VìPhúc ThọĐan PhượngHoài ĐứcQuốc OaiThạch ThấtChương MỹThanh OaiThường TínPhú XuyênỨng HòaMỹ ĐứcBắc Từ Liêm</value>
      <webElementGuid>dc8faf3a-8ab2-4d59-b33b-af05a1389300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bb-body&quot;)/div[@class=&quot;checkout ng-scope&quot;]/div[@class=&quot;step-container container step-infomation&quot;]/div[@class=&quot;step-one&quot;]/form[@class=&quot;ng-invalid ng-invalid-required ng-dirty ng-valid-parse ng-valid-pattern&quot;]/div[@class=&quot;col-md-12 col-sm-12 col-xs-12&quot;]/div[@class=&quot;box-block box-edit-delivery&quot;]/div[@class=&quot;box-item  validation-box&quot;]/div[@class=&quot;col-md-8 col-sm-8&quot;]/p[@class=&quot;select-block&quot;]/select[@id=&quot;dropEditWard&quot;]</value>
      <webElementGuid>90f298e1-2ada-4d4a-8e84-57acfff7775d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dropEditWard']</value>
      <webElementGuid>4232c8cb-99a7-406a-a1b3-cf2eb7fc8656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bb-body']/div/div/div/form/div[2]/div[2]/div[10]/div[2]/p/select</value>
      <webElementGuid>29a9605f-44a2-4363-b564-7a69d0970e07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::select[1]</value>
      <webElementGuid>719d00fe-5807-447b-b49e-7fd08718afe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/preceding::select[1]</value>
      <webElementGuid>747a3d48-20ba-4108-b81e-eaee8c9d1e7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[2]/p/select</value>
      <webElementGuid>89726b7e-764c-4253-8e67-fb22eb4a77ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'dropEditWard' and @name = 'dropEditWard' and (text() = 'Ba ĐìnhHoàn KiếmTây HồLong BiênCầu GiấyĐống ĐaHai Bà TrưngHoàng MaiThanh XuânSóc SơnĐông AnhGia LâmNam Từ LiêmThanh TrìMê LinhHà ĐôngSơn TâyBa VìPhúc ThọĐan PhượngHoài ĐứcQuốc OaiThạch ThấtChương MỹThanh OaiThường TínPhú XuyênỨng HòaMỹ ĐứcBắc Từ Liêm' or . = 'Ba ĐìnhHoàn KiếmTây HồLong BiênCầu GiấyĐống ĐaHai Bà TrưngHoàng MaiThanh XuânSóc SơnĐông AnhGia LâmNam Từ LiêmThanh TrìMê LinhHà ĐôngSơn TâyBa VìPhúc ThọĐan PhượngHoài ĐứcQuốc OaiThạch ThấtChương MỹThanh OaiThường TínPhú XuyênỨng HòaMỹ ĐứcBắc Từ Liêm')]</value>
      <webElementGuid>07bd1d45-3fc7-463e-9940-822e79f7cc99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
