<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_H Ch MinhH NiHi Phng NngCn ThAn Gian_0e93c8</name>
   <tag></tag>
   <elementGuidId>8234a44a-b812-4c1b-98e4-9d0566068860</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dropEditCity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dropEditCity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a4f5ef5c-a923-48ec-8901-7e307368bd00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-input input-text ng-pristine ng-untouched ng-valid ng-not-empty</value>
      <webElementGuid>ba9fdf3d-f521-4373-b0b1-bf467cde8e8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dropEditCity</value>
      <webElementGuid>ae6d8674-c6e5-4aff-acef-2ba4a09b596d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dropEditCity</value>
      <webElementGuid>9d2e85b4-2995-483e-a871-a6599dfe75a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>editUserAdress.Address.City</value>
      <webElementGuid>ac03fb62-e1c0-4504-8fb5-1ad4cfeaefd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-options</name>
      <type>Main</type>
      <value>option.Name for option in recCities track by option.ID</value>
      <webElementGuid>20eccad1-a7a7-449e-9265-3f40342b7924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>09d2f990-b1c6-4929-a1ea-fdb8d23049cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hồ Chí MinhHà NộiHải PhòngĐà NẵngCần ThơAn GiangBà Rịa - Vũng TàuBắc GiangBắc KạnBạc LiêuBắc NinhBến TreBình ĐịnhBình DươngBình PhướcBình ThuậnCà mauCao BằngĐắk LắkĐắk NôngĐiện BiênĐồng NaiĐồng ThápGia LaiHà GiangHà NamHà TĩnhHải DươngHậu GiangHòa BìnhHưng YênKhánh HòaKiên GiangKon TumLai ChâuLâm Đồng Lạng SơnLào CaiLong AnNam ĐịnhNghệ AnNinh BìnhNinh ThuậnPhú ThọPhú YênQuảng BìnhQuảng Nam Quảng NgãiQuảng NinhQuảng Trị Sóc TrăngSơn LaTây NinhThái BìnhThái NguyênThanh HóaThừa Thiên HuếTiền GiangTrà VinhTuyên QuangVĩnh LongVĩnh PhúcYên Bái</value>
      <webElementGuid>522ae458-538b-4fd0-b040-2c3830d08d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropEditCity&quot;)</value>
      <webElementGuid>9f6b500a-48f5-4021-becd-29f1333bf4a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dropEditCity']</value>
      <webElementGuid>716b4ee4-b79e-46b0-a617-34739785eac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bb-body']/div/div/div/form/div[2]/div[2]/div[8]/div[2]/p/select</value>
      <webElementGuid>046f3b01-8c52-4723-a03a-8236293d49fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::select[1]</value>
      <webElementGuid>385f8ec5-052a-49f6-9611-14079d119ff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/preceding::select[1]</value>
      <webElementGuid>fbaf691f-0a74-4176-a242-61ba42715a42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/p/select</value>
      <webElementGuid>77669cbd-cb82-4a77-97cf-e7a147406989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'dropEditCity' and @name = 'dropEditCity' and (text() = 'Hồ Chí MinhHà NộiHải PhòngĐà NẵngCần ThơAn GiangBà Rịa - Vũng TàuBắc GiangBắc KạnBạc LiêuBắc NinhBến TreBình ĐịnhBình DươngBình PhướcBình ThuậnCà mauCao BằngĐắk LắkĐắk NôngĐiện BiênĐồng NaiĐồng ThápGia LaiHà GiangHà NamHà TĩnhHải DươngHậu GiangHòa BìnhHưng YênKhánh HòaKiên GiangKon TumLai ChâuLâm Đồng Lạng SơnLào CaiLong AnNam ĐịnhNghệ AnNinh BìnhNinh ThuậnPhú ThọPhú YênQuảng BìnhQuảng Nam Quảng NgãiQuảng NinhQuảng Trị Sóc TrăngSơn LaTây NinhThái BìnhThái NguyênThanh HóaThừa Thiên HuếTiền GiangTrà VinhTuyên QuangVĩnh LongVĩnh PhúcYên Bái' or . = 'Hồ Chí MinhHà NộiHải PhòngĐà NẵngCần ThơAn GiangBà Rịa - Vũng TàuBắc GiangBắc KạnBạc LiêuBắc NinhBến TreBình ĐịnhBình DươngBình PhướcBình ThuậnCà mauCao BằngĐắk LắkĐắk NôngĐiện BiênĐồng NaiĐồng ThápGia LaiHà GiangHà NamHà TĩnhHải DươngHậu GiangHòa BìnhHưng YênKhánh HòaKiên GiangKon TumLai ChâuLâm Đồng Lạng SơnLào CaiLong AnNam ĐịnhNghệ AnNinh BìnhNinh ThuậnPhú ThọPhú YênQuảng BìnhQuảng Nam Quảng NgãiQuảng NinhQuảng Trị Sóc TrăngSơn LaTây NinhThái BìnhThái NguyênThanh HóaThừa Thiên HuếTiền GiangTrà VinhTuyên QuangVĩnh LongVĩnh PhúcYên Bái')]</value>
      <webElementGuid>1645df21-f51a-4382-933e-8128ee29e505</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
